### ISSUE TITLE
ubuntu_sim_ros_melodic.sh errors with 'Could not find a package configuration file provided by "geographic_msgs"' and "ImportError: No module named future"

### ISSUE THREAD

**Issue by jwang078** [PX4/PX4-Devguide#1063]
I am looking to use [build_scripts/ubuntu_sim_ros_melodic.sh](https://github.com/PX4/Devguide/blob/master/build_scripts/ubuntu_sim_ros_melodic.sh) in a Docker build script, but the script is ending in error. Are there prerequisites to using the script?

```
Installing GeographicLib geoids egm96-5
Installing GeographicLib gravity egm96
Installing GeographicLib magnetic emm2015
NOTICE: Could not determine the width of the terminal. A default width of 80 will be used. This warning will only be printed once.
-----------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/melodic
Workspace:                   /home/ubuntu/catkin_ws
-----------------------------------------------------------
Build Space:        [exists] /home/ubuntu/catkin_ws/build
Devel Space:        [exists] /home/ubuntu/catkin_ws/devel
Install Space:      [unused] /home/ubuntu/catkin_ws/install
Log Space:         [missing] /home/ubuntu/catkin_ws/logs
Source Space:       [exists] /home/ubuntu/catkin_ws/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-----------------------------------------------------------
[build] Found '6' packages in 0.0 seconds.                                     
[build] Updating package table.                                                
Starting >>> catkin_tools_prebuild                                             
Finished <<< catkin_tools_prebuild                [ 3.7 seconds ]              
Starting >>> mavlink                                                           
Starting >>> mavros_msgs                                                       
_______________________________________________________________________________
Errors << mavlink:make /home/ubuntu/catkin_ws/logs/mavlink/build.make.000.log  
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/ubuntu/catkin_ws/src/mavlink/pymavlink/generator/mavgen.py", line 12, in <module>
    from future import standard_library
ImportError: No module named future
make[2]: *** [uAvionix-v2.0-cxx-stamp] Error 1
make[1]: *** [CMakeFiles/uAvionix.xml-v2.0.dir/all] Error 2
make: *** [all] Error 2
cd /home/ubuntu/catkin_ws/build/mavlink; catkin build --get-env mavlink | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed << mavlink:make                          [ Exited with code 2 ]         
Failed <<< mavlink                              [ 0.3 seconds ]                
Abandoned <<< libmavconn                           [ Unrelated job failed ]    
Abandoned <<< mavros                               [ Unrelated job failed ]    
Abandoned <<< mavros_extras                        [ Unrelated job failed ]    
Abandoned <<< test_mavros                          [ Unrelated job failed ]    
_______________________________________________________________________________
Errors << mavros_msgs:cmake /home/ubuntu/catkin_ws/logs/mavros_msgs/build.cmake.000.log
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "geographic_msgs"
  with any of the following names:

    geographic_msgsConfig.cmake
    geographic_msgs-config.cmake

  Add the installation prefix of "geographic_msgs" to CMAKE_PREFIX_PATH or
  set "geographic_msgs_DIR" to a directory containing one of the above files.
  If "geographic_msgs" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


cd /home/ubuntu/catkin_ws/build/mavros_msgs; catkin build --get-env mavros_msgs | catkin env -si  /usr/bin/cmake /home/ubuntu/catkin_ws/src/mavros/mavros_msgs --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/ubuntu/catkin_ws/devel/.private/mavros_msgs -DCMAKE_INSTALL_PREFIX=/home/ubuntu/catkin_ws/install; cd -
...............................................................................
Failed << mavros_msgs:cmake                     [ Exited with code 1 ]         
Failed <<< mavros_msgs                          [ 2.4 seconds ]                
[build] Summary: 1 of 7 packages succeeded.                                    
[build] Ignored: None.                                                         
[build] Warnings: None.                                                        
[build] Abandoned: 4 packages were abandoned.                                  
[build] Failed: 2 packages failed.                                             
[build] Runtime: 6.3 seconds total.                                            
[build] Note: Workspace packages have changed, please re-source setup files to use them.
Removing intermediate container 410247b0fc07
```

Dockerfile

```
FROM dorowu/ubuntu-desktop-lxde-vnc:bionic

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1001 ubuntu

WORKDIR /home/ubuntu

USER root

RUN sudo apt update && sudo apt install -y wget vim python3-pip \
    && pip3 install future

# Install ROS Melodic
# Tested with this version https://raw.githubusercontent.com/PX4/Devguide/5e42a551ecb26a6fb77715f9f55f8075447d64d2/build_scripts/ubuntu_sim_ros_melodic.sh
RUN wget https://raw.githubusercontent.com/PX4/Devguide/master/build_scripts/ubuntu_sim_ros_melodic.sh
RUN /bin/bash -c "USER=ubuntu source ubuntu_sim_ros_melodic.sh"
RUN rm ubuntu_sim_ros_melodic.sh

```

**Comment by hamishwillee** [comment]
Closing, as this file has not been tested or designed to use in docker. I believe there are docker setup files in CI that may help - @TSC21 can you point to those?
