### ISSUE TITLE
Fail to Build DevGuide Doc

### ISSUE THREAD

**Issue by BrightSoulXYHY** [PX4/PX4-Devguide#894]
Hello I try to clone it and using gitbook to build for static html, but some errors occour
First I try to `gitbook build` it show the module `weak` is requird
```
$ gitbook build
info: parsing multilingual book, with 2 languages
info: 22 plugins are installed
info: 21 explicitly listed
info: loading plugin "youtube"... OK
info: loading plugin "richquotes"... OK
info: loading plugin "collapsible-menu"... OK
info: loading plugin "anchors"... OK
info: loading plugin "page-toc-button"... OK
info: loading plugin "ga"... OK
info: loading plugin "language-picker"... OK
info: loading plugin "custom-favicon"... OK
info: loading plugin "bulk-redirect"... OK
info: loading plugin "toolbar"... OK
info: loading plugin "validate-links"... OK
info: loading plugin "versions-select"... OK
info: loading plugin "mathjax"... OK
info: loading plugin "mermaid"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-dronecode"... OK
info: loading plugin "theme-default"... OK
info: found 749 asset files
warn: "options" property is deprecated, use config.get(key) instead
info:
info: generating language "en"
info: found 137 pages
info: found 7 asset files
warn: "book" property is deprecated, use "this" directly instead
warn: "this.generator" property is deprecated, use "this.output.name" instead
warn: "navigation" property is deprecated
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module 'weak'
Require stack:
- /mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/dnode/index.js
- /mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/phantom/phantom.js       - /mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/gitbook-plugin-mermaid/index.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/plugins/loadPlugin.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/plugins/loadForBook.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/plugins/index.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/api/encodeGlobal.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/api/index.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/output/getModifiers.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/output/json/onPage.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/output/json/index.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/output/index.js
- /home/brightsoul/.gitbook/versions/3.2.3/lib/index.js
- /usr/lib/node_modules/gitbook-cli/lib/local.js
- /usr/lib/node_modules/gitbook-cli/lib/index.js
- /usr/lib/node_modules/gitbook-cli/bin/gitbook.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)     at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at new D (/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/dnode/index.js:28:20)
    at module.exports (/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/dnode/index.js:8:12)
    at /mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/phantom/phantom.js:174:13
    at Server.handler (/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/shoe/index.js:22:9)
    at Server.emit (events.js:210:5)
    at App.emit (/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/sockjs/lib/sockjs.js:182:27) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/dnode/index.js',          '/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/phantom/phantom.js',      '/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/gitbook-plugin-mermaid/index.js',
    '/home/brightsoul/.gitbook/versions/3.2.3/lib/plugins/loadPlugin.js',           '/home/brightsoul/.gitbook/versions/3.2.3/lib/plugins/loadForBook.js',          '/home/brightsoul/.gitbook/versions/3.2.3/lib/plugins/index.js',
    '/home/brightsoul/.gitbook/versions/3.2.3/lib/api/encodeGlobal.js',
    '/home/brightsoul/.gitbook/versions/3.2.3/lib/api/index.js',
    '/home/brightsoul/.gitbook/versions/3.2.3/lib/output/getModifiers.js',          '/home/brightsoul/.gitbook/versions/3.2.3/lib/output/json/onPage.js',           '/home/brightsoul/.gitbook/versions/3.2.3/lib/output/json/index.js',            '/home/brightsoul/.gitbook/versions/3.2.3/lib/output/index.js',
    '/home/brightsoul/.gitbook/versions/3.2.3/lib/index.js',
    '/usr/lib/node_modules/gitbook-cli/lib/local.js',
    '/usr/lib/node_modules/gitbook-cli/lib/index.js',
    '/usr/lib/node_modules/gitbook-cli/bin/gitbook.js'
  ]
}
```
and I try to install weak some err like this
```
$ sudo npm install weak
[sudo] password for brightsoul:

> weak@1.0.1 install /mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/weak  > node-gyp rebuild

make: Entering directory '/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
../src/weakref.cc: In function ‘void {anonymous}::TargetCallback(const Nan::WeakCallbackInfo<{anonymous}::proxy_container>&)’:
../src/weakref.cc:147:73: error: no matching function for call to ‘v8::Function::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value> [1])’
   globalCallbackDirect->Call(Nan::GetCurrentContext()->Global(), 1, argv);                                                                              ^      In file included from /home/brightsoul/.cache/node-gyp/13.1.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/home/brightsoul/.cache/node-gyp/13.1.0/include/node/v8.h:4211:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(Local<Context> context,
                                           ^~~~
/home/brightsoul/.cache/node-gyp/13.1.0/include/node/v8.h:4211:43: note:   candidate expects 4 arguments, 3 provided
../src/weakref.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Create(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/weakref.cc:168:75: error: no matching function for call to ‘v8::ObjectTemplate::NewInstance()’
   Local<Object> proxy = Nan::New<ObjectTemplate>(proxyClass)->NewInstance();                                                                              ^    In file included from /home/brightsoul/.cache/node-gyp/13.1.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/home/brightsoul/.cache/node-gyp/13.1.0/include/node/v8.h:6286:44: note: candidate: v8::MaybeLocal<v8::Object> v8::ObjectTemplate::NewInstance(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);                                            ^~~~~~~~~~~
/home/brightsoul/.cache/node-gyp/13.1.0/include/node/v8.h:6286:44: note:   candidate expects 1 argument, 0 provided
../src/weakref.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::IsNearDeath(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/weakref.cc:223:55: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
   Local<Boolean> rtn = Nan::New<Boolean>(cont->target.IsNearDeath());
                                                       ^~~~~~~~~~~
weakref.target.mk:109: recipe for target 'Release/obj.target/weakref/src/weakref.o' failed
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
make: Leaving directory '/mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/weak/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/f/Progroming/_Doc_Src/PX4-Devguide/node_modules/weak
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/mnt/f/Progroming/_Doc_Src/PX4-Devguide/package.json'
npm WARN PX4-Devguide No description
npm WARN PX4-Devguide No repository field.
npm WARN PX4-Devguide No README data
npm WARN PX4-Devguide No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weak@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weak@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brightsoul/.npm/_logs/2019-11-18T14_45_53_155Z-debug.log
```
I try many methods but it does not work, Please Help me
and the version for nodejs 
```
$ npm -v
6.12.1
$ node -v
v13.1.0
```

Think you

**Comment by hamishwillee** [comment]
I build this on Ubuntu 16.04, and so does the docker build: https://github.com/PX4/containers/blob/master/docker/Dockerfile_docs

The issue is caused by the mermaid plugin. If you just want to do testing  (ie not for publishing) the easiest fix is to disable the mermaid plugin. This stops some sequence diagrams rendering but on 95% of pages you can render and see what is going on.

The change needs to be made here https://github.com/PX4/Devguide/blob/master/book.json#L22 - basically you move the "-" in front of mermaid and remove the one from stub-out ...
```
        "-mermaid",
        "stub-out-blocks@git+https://github.com/hamishwillee/gitbook-plugin-stub-out-blocks.git",
```

**Comment by BrightSoulXYHY** [comment]
Thanks a lot ，it dose work

**Comment by bys1123** [comment]
I met the same issue……

**Comment by bys1123** [comment]
https://github.com/chriswessels/gitbook-plugin-mermaid-gb3
I found a mermaid plugin for gitbook3 but it have a different syntax.

**Comment by bys1123** [comment]
https://github.com/miao1007/gitbook-plugin-mermaid-cli
this one looks good

**Comment by bys1123** [comment]
not good, it need chrome with X11 desktop

**Comment by bys1123** [comment]
reference https://github.com/JozoVilcek/gitbook-plugin-mermaid/issues/21
I use `n 4.2.6`
now everything is ok on 18.04

**Comment by hamishwillee** [comment]
FYI, I updated to Ubuntu LTS 18.04 and the build all works with the set of plugins in the devguide.

**Comment by bys1123** [comment]
I installed node 12 lts on my ubuntu, maybe that's the reason it's not work.

**Comment by hamishwillee** [comment]
Maybe. I used the node that comes when you just do `sudo apt install nodejs`

**Comment by bys1123** [comment]
That is node 8.10 I guess, I’ll try later.

**Comment by bys1123** [comment]
`gitbook build` progress will stop at
```
debug: generate page "concept/mixing.md" 
debug: calling hook "page:before" 
```
with node 8.10.0

**Comment by bys1123** [comment]
I tried a new server with apt installed nodejs, it fixed.

**Comment by bys1123** [comment]
Trying on old server, if run as "sudo" will stop at
```
debug: generate page "concept/mixing.md" 
debug: calling hook "page:before" 
phantom stdout: Incompatibile SockJS! Main site uses: "0.3.1.7.ga67f.dirty", the iframe: "0.3.4".

phantom stdout: Incompatibile SockJS! Main site uses: "0.3.1.7.ga67f.dirty", the iframe: "0.3.4".

debug: calling hook "page" 
debug: index page concept/mixing.md 
debug: generate page "concept/pwm_limit.md" 
debug: calling hook "page:before" 
debug: calling hook "page" 
debug: index page concept/pwm_limit.md 
debug: generate page "concept/system_startup.md" 
debug: calling hook "page:before" 
debug: calling hook "page" 
debug: index page concept/system_startup.md 
debug: generate page "simulation/README.md" 
debug: calling hook "page:before" 
debug: calling hook "page" 
debug: index page simulation/README.md 
debug: generate page "simulation/jmavsim.md" 
debug: calling hook "page:before" 
```

**Comment by bys1123** [comment]
`n 5.9.1` works fine. I‘ll use this. whatever, same result.
